# Use an official Node.js runtime as a base image
FROM node:18 as builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the container
COPY . .

# Build the project
RUN npm run dev

# Use a smaller base image for the production container
FROM nginx:alpine

# Copy the built files from the builder container to the Nginx container
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy the Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to the host machine
EXPOSE 80

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]
